INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1438, 'Bodegraven', '2411PV', 'Tolnasingel', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1439, 'Bodegraven', '1232AW', 'tt. Vasumweg', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1440, 'Den Helder', '1785LX', 'Ravelijncenter', 23, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1441, 'Alphen aan den Rijn', '2408BZ', 'Curieweg', 4, 'D');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1442, 'Eindhoven', '5652AG', 'de Witbogt', 26, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1443, NULL, '3765CA', NULL, 3, 'Bis');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1444, 'Amsterdam', '1046AV', 'Bolstoen ', 32, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1445, NULL, '3034ST', NULL, 120, 'A');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1446, 'Zwolle', '8041BL', 'Marsweg', 293, 'A');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1447, 'Posterholt', '6061AV', 'Julianalaan', 4, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1448, 'Nijmegen', '6546BE', 'Kerkenbos', 1224, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1449, 'Groningen', '9726AH', 'Emmasingel', 4, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1450, 'Valkenswaard', '5551DE', 'Korunahof', 18, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1451, 'Rijssen', '7462AP', 'Haarstraat', 8, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1452, 'Eindhoven ', '5611AZ', 'Emmasingel ', 33, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1453, 'Valkenswaard', '5555LH', 'De Vlasakker', 14, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1454, 'Amsterdam', '7825SB', 'H. Vasumweg ', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1455, 'Ewijk', '6644EC', 'Hoge Elt', 6, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1456, 'Emmen', '7826GD', 'Dagpauwoog', 2, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1457, 'Utrecht', '3527GA', 'Bernadottelaan ', 11, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1458, 'Amsterdam', '1040KC', 'Postbus ', 59141, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1459, 'Wormerveer', '1521PT', 'Rosbayerweg', 222, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1460, 'Rotterdam', '3051RB', 'Willem van Hillegaersbergstraat', 57, 'C');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1461, 'Bergen lb', '5854PA', 'Siebengewaldseweg ', 21, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1462, 'Veenendaal', '3905PB', 'Vendelier', 19, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1463, 'Veendam', '9641KJ', 'Lloydsweg', 41, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1464, 'Barendrecht', '2991LR', 'Tuindersweg', 34, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1465, 'Dedemsvaart', '7701SG', 'Archimedesstraat', 14, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1466, 'Nha Trang', '3051RB', 'Nha Trang', 57, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1467, 'hoogeveen', '7905SP', 'buitenvaart', 1706, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1468, 'Venlo', '5928RT', 'De Gruisdonk', 45, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1469, 'Roermond', '6041HP', 'Willem II Singel', 29, 'A');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1470, 'Roosendaal', '4704SV', 'klerkenveld', 14, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1471, 'Mill', '5451JK', 'Langenboomseweg', 22, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1472, '\'s-Gravenhage', '2596AL', 'Zuid-Hollandlaan', 7, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1473, 'Amsterdam', '1097DP', 'Mr. Treublaan ', 3, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1474, 'Venlo', '5911EW', 'Maaskade', 27, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1475, 'Amstelveen', '1181BN', 'Kalfjeslaan', 45, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1476, 'Venlo', '5911EW', 'Maaskade', 27, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1477, 'rijswijk', '2281CX', 'geestbrugkade', 32, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1478, 'Emmen', '9531MC', 'Westeind', 50, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1479, NULL, '3846 AN', NULL, 5, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1480, 'Venlo', '5916PG', 'Veegtesstraat', 41, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1481, 'Alkmaar', '1815VN', 'van der kaaijstraat ', 64, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1482, 'Apeldoorn', '7311LR', 'Marktplein', 44, '8');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1483, 'Horst', '5961XK', 'Willem-Alexanderstraat', 5, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1484, 'Nieuwegein', '3432GN', 'Merweplein', 9, '4');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1485, NULL, '7141XJ', NULL, 16, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1486, 'Utrecht', '3500BN', 'Vleutensevaart', 100, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1487, 'Weert', '6002AM', 'Boshoverweg', 85, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1488, 'Veghel', '5463GA', 'Van Heemskerkstraat', 23, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1489, NULL, '2408AN', NULL, 36, 'B7');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1490, 'Nieuw en Sintjoosland', '4339AP', 'Hoge Stelle', 47, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1491, 'Groningen', '9723LD', 'Annastraat', 5, 'a');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1492, 'Roermond', '6041DA', 'de Lombardije', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1493, 'Loosdrecht', '1231KB', 'Rading', 48, 'A');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1494, 'Dronten', '8253PS', 'De Dieze', 26, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1495, 'Stadskanaal', '9501RW', 'Hazebroeklaan', 15, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1496, NULL, '1097DP', NULL, 3, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1497, 'Venray', '5804AL', 'Mackenhof ', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1498, 'UTRECHT', '3542AA', 'Atoomweg', 63, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1499, 'Enschede', '7521PL', 'Capitool', 10, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1500, 'Kollum', '9291MA', 'Mr Andreaestraat', 7, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1501, 'Nieuw Bergen', '5854AV', 'Rijksweg', 24, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1502, NULL, '5428NV', NULL, 15, 'A');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1503, 'Zwolle', '8042PJ', 'Schoenerweg ', 1, 'B');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1504, 'Assen', '9407PA', 'Dillanden', 11, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1505, 'PAPENDRECHT', '3353HE', 'Overtoompassage ', 2, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1506, 'Enschede', '7512ZP', 'Floresstraat', 77, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1507, 'Amsterdam', '1101CD', 'Hogehilweg', 14, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1508, NULL, '8911LE', NULL, 3, 'B');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1509, 'Werkendam', '4251LV', 'Dieplood', 26, 'B');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1510, 'Utrecht', '3555JW', 'Jacob Jonkerlaan ', 5, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1511, 'Honselersdijk', '2675RE', 'Biesbos ', 2, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1512, 'Hilversum', '1213NS', 'Olympia', 1, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1513, 'Breda', '4815HS', 'Spinveld', 12, 'A');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1514, 'Heerenveen', '8441BA', 'Herenwal ', 40, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1515, 'Dalfsen', '7722GA', 'De Vesting', 29, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1516, 'Delft', '2613HJ', 'Isaak Hoornbeekstraat', 50, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1517, 'Breda', '4811CA', 'Ceresstraat', 13, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1518, 'Zoetermeer', '2728PD', 'Slootweg', 1, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1519, 'Enschede', '7521RB', 'Rigtersbleek Aalten ', 4, 'K0.01');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1520, 'Nijmegen', '6531JC', 'Groenstraat ', 294, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1521, 'Emmen', '7811ME', 'Westeind', 50, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1522, 'Almelo ', '7607XJ', 'Brugstraat', 11, '1.13');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1523, NULL, '2152AB', NULL, 186, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1524, 'Amsterdam', '1033SH', 'Joop Geesinkweg ', 122, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1525, 'Steenwijk', '8332JZ', 'Oostermeentherand', 2, 'E');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1526, 'Amsterdam', '1033MV', 'Netwerkweg', 17, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1527, 'Nijmegen', '6531JC', 'Groenstraat', 294, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1528, '\'s-Hertogenbosch', '5215MV', 'Het Zuiderkruis', 63, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1529, 'Dieden', '5353KL', 'Weijenstraat ', 10, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1530, 'Nijkerkerveen', '3864PT', 'Dijkje ', 6, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1531, 'Veldhoven', '5507TR', 'Habraken', 2601, 'unit 3');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1532, 'Arnhem', '6846XC', 'Orpheusstraat', 8, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1533, 'Valkenswaard', '5554HN', 'Corridor', 38, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1534, 'Bergen', '5854PA', 'Siebengewaldseweg', 21, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1535, NULL, '4811CA', NULL, 13, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1536, 'Groningen', '9723BE', 'Osloweg', 1, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1537, 'Bergen L', '5854HT', 'Buizerdstraat', 6, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1538, 'Eindhoven', '5611ED', 'Jan van Hooffstraat', 8, 'C');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1539, 'Leeuwarden', '8925LE', 'Rispensstate ', 3, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1540, NULL, '5611AZ', NULL, 33, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1541, 'Enschede', '7524NT', 'Hasselerweg', 4, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1542, 'Eindhoven', '5611ED', 'Jan van Hooffstraat', 8, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1543, 'Wormer', '1531NX', 'Koetserstraat ', 10, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1544, 'Valklens', '5554HG', 'Kerkhofstraat', 21, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1545, 'Rotterdam', '3011VW', 'Jufferkade', 81, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1546, 'ALmere', '1313BX', 'Kweekgrasstraat', 30, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1547, '40', '1687WB', 'Kropaar', 40, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1548, 'Den Bosch', '5235AB', 'Burgemeesters Godschalxstraat', 59, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1549, 'Den Dungen', '5275CE', 'Bogerd', 4, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1550, '\'s-Hertogenbosch', '2411PV', 'Burgemeesters Godschalxstraat', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1551, 'Bodegraven', '2411PV', 'Tolnasingel', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1552, 'Wierden', '7641AB', 'Nijverheidsstraat', 8, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1553, 'Ede', '6718MX', 'Bosveen', 2, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1554, 'Utrecht', '3512VV', 'Oudegracht', 11, '  B');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1555, 'Amsterdam', '1101CB', 'Hogehilweg', 19, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1556, 'Ommel', '5724AE', 'Kluisstraat', 30, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1557, 'Den Haag', '2492ND', 'Spieringdam ', 2, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (1558, 'Weesp', '1381HB', 'Horn', 763, 'S');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (3823, 'Bodegraven', '2411 PV', 'Tolnasingel ', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (3824, 'Heerenveen', '8447SN', 'Innovatielaan', 25, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (3825, 'Bodegraven', '2411PV', 'Tolnasingel', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (3826, 'Delft', '2612PA', 'Poortweg', 4, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (3827, NULL, '9672AS', NULL, 26, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (3828, NULL, '5103PN', NULL, 7, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (3829, NULL, '3881LS', NULL, 42, 'A');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (3830, 'Bodegraven', '2411PV', 'Tolnasingel', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (3831, NULL, '3821AG', NULL, 48, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (3832, NULL, '5133CK', NULL, 21, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (7200, NULL, '7201KE', NULL, 41, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (7201, NULL, '7201KE', NULL, 41, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (7217, NULL, '2495AL', NULL, 5, '96');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (9298, NULL, '5042XK', NULL, 8, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (15563, NULL, '6842CV', NULL, 6, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (15583, 'Monster', '2681DR', 'Hartschelp', 32, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (17701, 'Hilversum', '1213NS', 'Olympia', 1, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (17740, NULL, '1019 BR', NULL, 27, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (20938, NULL, '7608JW', NULL, 22, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (21142, NULL, '1703MP', NULL, 17, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (24821, NULL, '5617BD', NULL, 32, '10 5e verdieping');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (24919, 'Bodegraven', '2411PV', 'Tolnasingel', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (25263, NULL, '1051KH', NULL, 21, 'C');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (26205, NULL, '1077ZX', NULL, 4117, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (26850, NULL, '1032KJ', NULL, 34, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (43271, NULL, '8262WM', NULL, 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (52150, NULL, '9697SM', NULL, 43, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (54092, 'Bodegraven', '2411PV', 'Tolnasingel', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (59575, 'Bodegraven', '2411PV', 'Tolnasingel', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (62997, 'Amsterdam', '1077ZX', 'Strawinskylaan', 4117, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (72866, 'Bodegraven', '2411PV', 'Tolnasingel', 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (72867, NULL, '2411PV', NULL, 12, '');
INSERT IGNORE INTO `billing_addresses` (`id`, `city`, `zipcode`, `street`, `house_number`, `house_number_ext`) VALUES (79957, NULL, '3882HS', NULL, 9, '');
